### ISSUE TITLE
Check for Gutenberg to be active before calling register_block_type()

### ISSUE THREAD

**Issue by zackkatz** [zgordon/how-to-gutenberg-plugin#2]
Just spinning up a new site and didn't have Gutenberg activated yet. Got a fatal error:

> `( ! ) Fatal error: Uncaught Error: Call to undefined function register_block_type() in /app/public/wp-content/plugins/jsforwp-how-to-gutenberg/jsforwp-how-to-gutenberg.php on line 130`

Maybe an admin notice would be a helpful reminder.

**Comment by zgordon** [comment]
Thanks for this!  Just fixed :)
